USE EJERCICIO26PROVINCIAS;
CREATE TABLE PERSONAS(
	DNI CHAR(8) NOT NULL PRIMARY KEY,
	nombre_peson VARCHAR(18),
	direccion_person VARCHAR(18),
	poblacion_person VARCHAR(18),
	
	COD_PROVINCIA INT,
	CONSTRAINT COD_PROVINCIA FOREIGN KEY (COD_PROVINCIA) REFERENCES PROVINCIAS26(COD_PROVINCIA) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);