DROP DATABASE IF EXISTS EJERCICIO26PERSONAS;
CREATE DATABASE EJERCICIO26PERSONAS;
USE EJERCICIO26PERSONAS;
CREATE TABLE PERSONAS(
	DNI CHAR(8) NOT NULL PRIMARY KEY,
	nombre_peson VARCHAR(18),
	direccion_person VARCHAR(18),
	poblacion_person VARCHAR(18),

	COD_PROVINCIA INT,
	CONSTRAINT COD_PROVINCIA_FK FOREIGN KEY (COD_PROVINCIA) REFERENCES EJERCICIO26PROVINCIAS.PROVINCIAS26(COD_PROVINCIA) 
	ON UPDATE CASCADE 
	ON DELETE CASCADE
);